services:
  api:
    build: ./services/api
    image: saranda06/api-examen2:latest

  pdf-generator:
    build: ./services/pdf-generator
    image: saranda06/pdf-generator-examen2:latest

  notifier:
    build: ./services/notifier
    image: saranda06/notifier-examen2:latest

  receipt-worker:
    build: ./services/receipt-worker
    image: saranda06/receipt-worker-examen2:latest