apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-deployment
  labels:
    app: notifier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
        - name: notifier
          image: saranda06/notifier-examen2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: examen2-config