apiVersion: v1
kind: Service
metadata:
  name: notifier-service
  labels:
    app: notifier
spec:
  type: ClusterIP
  selector:
    app: notifier
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082