apiVersion: v1
kind: Service
metadata:
  name: pdf-generator-service
  labels:
    app: pdf-generator
spec:
  type: ClusterIP
  selector:
    app: pdf-generator
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081